services:
  postgres:
    image: postgres:latest
    container_name: identity-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  identity-service:
    build:
      context: ../../services/identity-service  # Point to the correct service directory
      dockerfile: Dockerfile  # Ensure it's picking the correct Dockerfile
    container_name: identity-service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/identity?schema=public"
    ports:
      - "3000:3000"
    volumes:
      - ../../services/identity-service:/app
    command: ["npm", "run", "start:dev"] 

volumes:
  pgdata:

