services:
# ✅ Shared Services
  postgres:
    image: postgres:latest
    container_name: identity-db
    restart: always
    env_file:
      - .env.${NODE_ENV}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5

# ✅ Microservices (Each One Only Uses Its Needed Dependencies)
  identity-service:
    build:
      context: ../../microservices/identity-service
      dockerfile: Dockerfile
    container_name: identity-service
    image: myapp/identity-service:latest
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env.${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ../../microservices/identity-service:/app
      - /app/node_modules
    command: ["npm", "run", "start"] 

volumes:
  pgdata: