### Test sample Database Endpoint
GET http://localhost:3000/api/sample/database
Accept: application/json

### Test sample external API Endpoint
GET http://localhost:3000/api/sample/external
Accept: application/json

### Post sample to Hello Endpoint
POST http://localhost:3000/api/sample
{
    "message": "Hello, World!"
}